---

version: '3.2'
services:

  pdnd-landing:
    container_name: pdnd-landing
    image: teamdigitale/pdnd-landing
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
